name: Releasing
run-name: ${{ github.actor }} is creating a new release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set manifest.json version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '0.0.0'
          replace: ${{ env.RELEASE_VERSION }}
          include: "manifest.json"
      - name: Installing dependencies
        run: yarn install
      - name: Building
        run: yarn build
      - name: Creating release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip dir manifest.json
      - name: Pushing release
        uses: softprops/action-gh-release@v1
        with:
          files: build.zip
